<?php
/**
* Imacons Defaults
*
* @package Imacon
*/

namespace Lambry\Imacon;

defined( 'ABSPATH' ) || exit;

/* Defaults Class */
class Defaults {

    /**
    * Placeholder
    *
    * @access public
    * @return string $placeholder
    */
    public static function placeholder() {

        $placeholder = 'data:image/svg+xml;base64,PHN2ZyBmaWxsPSIjOTk5IiB3aWR0aD0iNzUiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDU1MC44MDEgNTUwLjgiPjxwYXRoIGQ9Ik01MTUuODI4IDYxLjJIMzQuOTcyQzE1LjY2IDYxLjIgMCA3Ni44NiAwIDk2LjE3M1Y0NTQuNjNjMCAxOS4zMTIgMTUuNjYgMzQuOTcgMzQuOTcyIDM0Ljk3aDQ4MC44NTZjMTkuMzE0IDAgMzQuOTczLTE1LjY1OCAzNC45NzMtMzQuOTdWOTYuMTdjMC0xOS4zMTMtMTUuNjU3LTM0Ljk3LTM0Ljk3Mi0zNC45N3ptMCAzNC45NzJWMzUwLjUxbC02OC45Mi02Mi42NmMtMTAuMzYtOS40MTYtMjYuMjktOS4wNC0zNi4xODYuODY2bC02OS43NTIgNjkuNzRMMjAzLjQzOCAxOTQuMThjLTEwLjM5Ni0xMi40MTYtMjkuNDM4LTEyLjUzOC0zOS45OS0uMjcyTDM0Ljk3MiAzNDMuMjE4Vjk2LjE3M2g0ODAuODU2em0tMTQ4LjYyNyA5MS44YzAtMjYuNTYgMjEuNTI0LTQ4LjA4NiA0OC4wODUtNDguMDg2IDI2LjU2MiAwIDQ4LjA4NiAyMS41MjUgNDguMDg2IDQ4LjA4NiAwIDI2LjU2LTIxLjUyMiA0OC4wODUtNDguMDg1IDQ4LjA4NS0yNi41NiAwLTQ4LjA4NC0yMS41MjQtNDguMDg0LTQ4LjA4NXoiPjwvcGF0aD48L3N2Zz4=';

        return apply_filters( 'imacon/placeholder', $placeholder );

    }

    /**
    * Fields
    *
    * @access public
    * @return array $fields
    */
    public static function fields() {

        $fields = array_map( function( $field ) {
            return ( isset( $field['label'] ) ) ? $field['label']  : key( $field );
        }, Setup::fields() );

        return apply_filters( 'imacon/fields', $fields );

    }

    /**
    * Sizes
    *
    * @access public
    * @return array $sizes
    */
    public static function sizes() {

        $sizes = [];
        $sizes_list = get_intermediate_image_sizes();

        foreach ( $sizes_list as $size ) {
            $sizes[$size] = ucwords( str_replace( '_', ' ', $size ) );
        }
        $sizes['full'] = 'Full';

        return apply_filters( 'imacon/sizes', $sizes );

    }

    /**
    * Icons
    *
    * @access public
    * @return array $icons
    */
    public static function icons() {

        $icons = [
            '500px' => __( '500px', 'shorts' ),
            'fa fa-adjust' => __( 'adjust', 'shorts' ),
            'fa fa-adn' => __( 'App.net', 'shorts' ),
            'fa fa-align-center' => __( 'align-center', 'shorts' ),
            'fa fa-align-justify' => __( 'align-justify', 'shorts' ),
            'fa fa-align-left' => __( 'align-left', 'shorts' ),
            'fa fa-align-right' => __( 'align-right', 'shorts' ),
            'fa fa-amazon' => __( 'Amazon', 'shorts' ),
            'fa fa-ambulance' => __( 'ambulance', 'shorts' ),
            'fa fa-american-sign-language-interpreting' => __( 'American Sign Language Interpreting', 'shorts' ),
            'fa fa-anchor' => __( 'Anchor', 'shorts' ),
            'fa fa-android' => __( 'Android', 'shorts' ),
            'fa fa-angellist' => __( 'AngelList', 'shorts' ),
            'fa fa-angle-double-down' => __( 'Angle Double Down', 'shorts' ),
            'fa fa-angle-double-left' => __( 'Angle Double Left', 'shorts' ),
            'fa fa-angle-double-right' => __( 'Angle Double Right', 'shorts' ),
            'fa fa-angle-double-up' => __( 'Angle Double Up', 'shorts' ),
            'fa fa-angle-down' => __( 'angle-down', 'shorts' ),
            'fa fa-angle-left' => __( 'angle-left', 'shorts' ),
            'fa fa-angle-right' => __( 'angle-right', 'shorts' ),
            'fa fa-angle-up' => __( 'angle-up', 'shorts' ),
            'fa fa-apple' => __( 'Apple', 'shorts' ),
            'fa fa-archive' => __( 'Archive', 'shorts' ),
            'fa fa-area-chart' => __( 'Area Chart', 'shorts' ),
            'fa fa-arrow-circle-down' => __( 'Arrow Circle Down', 'shorts' ),
            'fa fa-arrow-circle-left' => __( 'Arrow Circle Left', 'shorts' ),
            'fa fa-arrow-circle-o-down' => __( 'Arrow Circle Outlined Down', 'shorts' ),
            'fa fa-arrow-circle-o-left' => __( 'Arrow Circle Outlined Left', 'shorts' ),
            'fa fa-arrow-circle-o-right' => __( 'Arrow Circle Outlined Right', 'shorts' ),
            'fa fa-arrow-circle-o-up' => __( 'Arrow Circle Outlined Up', 'shorts' ),
            'fa fa-arrow-circle-right' => __( 'Arrow Circle Right', 'shorts' ),
            'fa fa-arrow-circle-up' => __( 'Arrow Circle Up', 'shorts' ),
            'fa fa-arrow-down' => __( 'arrow-down', 'shorts' ),
            'fa fa-arrow-left' => __( 'arrow-left', 'shorts' ),
            'fa fa-arrow-right' => __( 'arrow-right', 'shorts' ),
            'fa fa-arrow-up' => __( 'arrow-up', 'shorts' ),
            'fa fa-arrows' => __( 'Arrows', 'shorts' ),
            'fa fa-arrows-alt' => __( 'Arrows Alt', 'shorts' ),
            'fa fa-arrows-h' => __( 'Arrows Horizontal', 'shorts' ),
            'fa fa-arrows-v' => __( 'Arrows Vertical', 'shorts' ),
            'fa fa-assistive-listening-systems' => __( 'Assistive Listening Systems', 'shorts' ),
            'fa fa-asterisk' => __( 'asterisk', 'shorts' ),
            'fa fa-at' => __( 'At', 'shorts' ),
            'fa fa-audio-description' => __( 'Audio Description', 'shorts' ),
            'fa fa-backward' => __( 'backward', 'shorts' ),
            'fa fa-balance-scale' => __( 'Balance Scale', 'shorts' ),
            'fa fa-ban' => __( 'ban', 'shorts' ),
            'fa fa-bar-chart' => __( 'Bar Chart', 'shorts' ),
            'fa fa-barcode' => __( 'barcode', 'shorts' ),
            'fa fa-bars' => __( 'Bars', 'shorts' ),
            'fa fa-battery-empty' => __( 'Battery Empty', 'shorts' ),
            'fa fa-battery-full' => __( 'Battery Full', 'shorts' ),
            'fa fa-battery-half' => __( 'Battery 1/2 Full', 'shorts' ),
            'fa fa-battery-quarter' => __( 'Battery 1/4 Full', 'shorts' ),
            'fa fa-battery-three-quarters' => __( 'Battery 3/4 Full', 'shorts' ),
            'fa fa-bed' => __( 'Bed', 'shorts' ),
            'fa fa-beer' => __( 'beer', 'shorts' ),
            'fa fa-behance' => __( 'Behance', 'shorts' ),
            'fa fa-behance-square' => __( 'Behance Square', 'shorts' ),
            'fa fa-bell' => __( 'bell', 'shorts' ),
            'fa fa-bell-o' => __( 'Bell Outlined', 'shorts' ),
            'fa fa-bell-slash' => __( 'Bell Slash', 'shorts' ),
            'fa fa-bell-slash-o' => __( 'Bell Slash Outlined', 'shorts' ),
            'fa fa-bicycle' => __( 'Bicycle', 'shorts' ),
            'fa fa-binoculars' => __( 'Binoculars', 'shorts' ),
            'fa fa-birthday-cake' => __( 'Birthday Cake', 'shorts' ),
            'fa fa-bitbucket' => __( 'Bitbucket', 'shorts' ),
            'fa fa-bitbucket-square' => __( 'Bitbucket Square', 'shorts' ),
            'fa fa-black-tie' => __( 'Font Awesome Black Tie', 'shorts' ),
            'fa fa-blind' => __( 'Blind', 'shorts' ),
            'fa fa-bluetooth' => __( 'Bluetooth', 'shorts' ),
            'fa fa-bluetooth-b' => __( 'Bluetooth', 'shorts' ),
            'fa fa-bold' => __( 'bold', 'shorts' ),
            'fa fa-bolt' => __( 'Lightning Bolt', 'shorts' ),
            'fa fa-bomb' => __( 'Bomb', 'shorts' ),
            'fa fa-book' => __( 'book', 'shorts' ),
            'fa fa-bookmark' => __( 'bookmark', 'shorts' ),
            'fa fa-bookmark-o' => __( 'Bookmark Outlined', 'shorts' ),
            'fa fa-braille' => __( 'Braille', 'shorts' ),
            'fa fa-briefcase' => __( 'Briefcase', 'shorts' ),
            'fa fa-btc' => __( 'Bitcoin (BTC)', 'shorts' ),
            'fa fa-bug' => __( 'Bug', 'shorts' ),
            'fa fa-building' => __( 'Building', 'shorts' ),
            'fa fa-building-o' => __( 'Building Outlined', 'shorts' ),
            'fa fa-bullhorn' => __( 'bullhorn', 'shorts' ),
            'fa fa-bullseye' => __( 'Bullseye', 'shorts' ),
            'fa fa-bus' => __( 'Bus', 'shorts' ),
            'fa fa-buysellads' => __( 'BuySellAds', 'shorts' ),
            'fa fa-calculator' => __( 'Calculator', 'shorts' ),
            'fa fa-calendar' => __( 'calendar', 'shorts' ),
            'fa fa-calendar-check-o' => __( 'Calendar Check Outlined', 'shorts' ),
            'fa fa-calendar-minus-o' => __( 'Calendar Minus Outlined', 'shorts' ),
            'fa fa-calendar-o' => __( 'calendar-o', 'shorts' ),
            'fa fa-calendar-plus-o' => __( 'Calendar Plus Outlined', 'shorts' ),
            'fa fa-calendar-times-o' => __( 'Calendar Times Outlined', 'shorts' ),
            'fa fa-camera' => __( 'camera', 'shorts' ),
            'fa fa-camera-retro' => __( 'camera-retro', 'shorts' ),
            'fa fa-car' => __( 'Car', 'shorts' ),
            'fa fa-caret-down' => __( 'Caret Down', 'shorts' ),
            'fa fa-caret-left' => __( 'Caret Left', 'shorts' ),
            'fa fa-caret-right' => __( 'Caret Right', 'shorts' ),
            'fa fa-caret-square-o-down' => __( 'Caret Square Outlined Down', 'shorts' ),
            'fa fa-caret-square-o-left' => __( 'Caret Square Outlined Left', 'shorts' ),
            'fa fa-caret-square-o-right' => __( 'Caret Square Outlined Right', 'shorts' ),
            'fa fa-caret-square-o-up' => __( 'Caret Square Outlined Up', 'shorts' ),
            'fa fa-caret-up' => __( 'Caret Up', 'shorts' ),
            'fa fa-cart-arrow-down' => __( 'Shopping Cart Arrow Down', 'shorts' ),
            'fa fa-cart-plus' => __( 'Add to Shopping Cart', 'shorts' ),
            'fa fa-cc' => __( 'Closed Captions', 'shorts' ),
            'fa fa-cc-amex' => __( 'American Express Credit Card', 'shorts' ),
            'fa fa-cc-diners-club' => __( 'Diner\'s Club Credit Card', 'shorts' ),
            'fa fa-cc-discover' => __( 'Discover Credit Card', 'shorts' ),
            'fa fa-cc-jcb' => __( 'JCB Credit Card', 'shorts' ),
            'fa fa-cc-mastercard' => __( 'MasterCard Credit Card', 'shorts' ),
            'fa fa-cc-paypal' => __( 'Paypal Credit Card', 'shorts' ),
            'fa fa-cc-stripe' => __( 'Stripe Credit Card', 'shorts' ),
            'fa fa-cc-visa' => __( 'Visa Credit Card', 'shorts' ),
            'fa fa-certificate' => __( 'certificate', 'shorts' ),
            'fa fa-chain-broken' => __( 'Chain Broken', 'shorts' ),
            'fa fa-check' => __( 'Check', 'shorts' ),
            'fa fa-check-circle' => __( 'Check Circle', 'shorts' ),
            'fa fa-check-circle-o' => __( 'Check Circle Outlined', 'shorts' ),
            'fa fa-check-square' => __( 'Check Square', 'shorts' ),
            'fa fa-check-square-o' => __( 'Check Square Outlined', 'shorts' ),
            'fa fa-chevron-circle-down' => __( 'Chevron Circle Down', 'shorts' ),
            'fa fa-chevron-circle-left' => __( 'Chevron Circle Left', 'shorts' ),
            'fa fa-chevron-circle-right' => __( 'Chevron Circle Right', 'shorts' ),
            'fa fa-chevron-circle-up' => __( 'Chevron Circle Up', 'shorts' ),
            'fa fa-chevron-down' => __( 'chevron-down', 'shorts' ),
            'fa fa-chevron-left' => __( 'chevron-left', 'shorts' ),
            'fa fa-chevron-right' => __( 'chevron-right', 'shorts' ),
            'fa fa-chevron-up' => __( 'chevron-up', 'shorts' ),
            'fa fa-child' => __( 'Child', 'shorts' ),
            'fa fa-chrome' => __( 'Chrome', 'shorts' ),
            'fa fa-circle' => __( 'Circle', 'shorts' ),
            'fa fa-circle-o' => __( 'Circle Outlined', 'shorts' ),
            'fa fa-circle-o-notch' => __( 'Circle Outlined Notched', 'shorts' ),
            'fa fa-circle-thin' => __( 'Circle Outlined Thin', 'shorts' ),
            'fa fa-clipboard' => __( 'Clipboard', 'shorts' ),
            'fa fa-clock-o' => __( 'Clock Outlined', 'shorts' ),
            'fa fa-clone' => __( 'Clone', 'shorts' ),
            'fa fa-cloud' => __( 'Cloud', 'shorts' ),
            'fa fa-cloud-download' => __( 'Cloud Download', 'shorts' ),
            'fa fa-cloud-upload' => __( 'Cloud Upload', 'shorts' ),
            'fa fa-code' => __( 'Code', 'shorts' ),
            'fa fa-code-fork' => __( 'code-fork', 'shorts' ),
            'fa fa-codepen' => __( 'Codepen', 'shorts' ),
            'fa fa-codiepie' => __( 'Codie Pie', 'shorts' ),
            'fa fa-coffee' => __( 'Coffee', 'shorts' ),
            'fa fa-cog' => __( 'cog', 'shorts' ),
            'fa fa-cogs' => __( 'cogs', 'shorts' ),
            'fa fa-columns' => __( 'Columns', 'shorts' ),
            'fa fa-comment' => __( 'comment', 'shorts' ),
            'fa fa-comment-o' => __( 'comment-o', 'shorts' ),
            'fa fa-commenting' => __( 'Commenting', 'shorts' ),
            'fa fa-commenting-o' => __( 'Commenting Outlined', 'shorts' ),
            'fa fa-comments' => __( 'comments', 'shorts' ),
            'fa fa-comments-o' => __( 'comments-o', 'shorts' ),
            'fa fa-compass' => __( 'Compass', 'shorts' ),
            'fa fa-compress' => __( 'Compress', 'shorts' ),
            'fa fa-connectdevelop' => __( 'Connect Develop', 'shorts' ),
            'fa fa-contao' => __( 'Contao', 'shorts' ),
            'fa fa-copyright' => __( 'Copyright', 'shorts' ),
            'fa fa-creative-commons' => __( 'Creative Commons', 'shorts' ),
            'fa fa-credit-card' => __( 'credit-card', 'shorts' ),
            'fa fa-credit-card-alt' => __( 'Credit Card', 'shorts' ),
            'fa fa-crop' => __( 'crop', 'shorts' ),
            'fa fa-crosshairs' => __( 'Crosshairs', 'shorts' ),
            'fa fa-css3' => __( 'CSS 3 Logo', 'shorts' ),
            'fa fa-cube' => __( 'Cube', 'shorts' ),
            'fa fa-cubes' => __( 'Cubes', 'shorts' ),
            'fa fa-cutlery' => __( 'Cutlery', 'shorts' ),
            'fa fa-dashcube' => __( 'DashCube', 'shorts' ),
            'fa fa-database' => __( 'Database', 'shorts' ),
            'fa fa-deaf' => __( 'Deaf', 'shorts' ),
            'fa fa-delicious' => __( 'Delicious Logo', 'shorts' ),
            'fa fa-desktop' => __( 'Desktop', 'shorts' ),
            'fa fa-deviantart' => __( 'deviantART', 'shorts' ),
            'fa fa-diamond' => __( 'Diamond', 'shorts' ),
            'fa fa-digg' => __( 'Digg Logo', 'shorts' ),
            'fa fa-dot-circle-o' => __( 'Dot Circle Outlined', 'shorts' ),
            'fa fa-download' => __( 'Download', 'shorts' ),
            'fa fa-dribbble' => __( 'Dribbble', 'shorts' ),
            'fa fa-dropbox' => __( 'Dropbox', 'shorts' ),
            'fa fa-drupal' => __( 'Drupal Logo', 'shorts' ),
            'fa fa-edge' => __( 'Edge Browser', 'shorts' ),
            'fa fa-eject' => __( 'eject', 'shorts' ),
            'fa fa-ellipsis-h' => __( 'Ellipsis Horizontal', 'shorts' ),
            'fa fa-ellipsis-v' => __( 'Ellipsis Vertical', 'shorts' ),
            'fa fa-empire' => __( 'Galactic Empire', 'shorts' ),
            'fa fa-envelope' => __( 'Envelope', 'shorts' ),
            'fa fa-envelope-o' => __( 'Envelope Outlined', 'shorts' ),
            'fa fa-envelope-square' => __( 'Envelope Square', 'shorts' ),
            'fa fa-envira' => __( 'Envira Gallery', 'shorts' ),
            'fa fa-eraser' => __( 'eraser', 'shorts' ),
            'fa fa-eur' => __( 'Euro (EUR)', 'shorts' ),
            'fa fa-exchange' => __( 'Exchange', 'shorts' ),
            'fa fa-exclamation' => __( 'exclamation', 'shorts' ),
            'fa fa-exclamation-circle' => __( 'Exclamation Circle', 'shorts' ),
            'fa fa-exclamation-triangle' => __( 'Exclamation Triangle', 'shorts' ),
            'fa fa-expand' => __( 'Expand', 'shorts' ),
            'fa fa-expeditedssl' => __( 'ExpeditedSSL', 'shorts' ),
            'fa fa-external-link' => __( 'External Link', 'shorts' ),
            'fa fa-external-link-square' => __( 'External Link Square', 'shorts' ),
            'fa fa-eye' => __( 'Eye', 'shorts' ),
            'fa fa-eye-slash' => __( 'Eye Slash', 'shorts' ),
            'fa fa-eyedropper' => __( 'Eyedropper', 'shorts' ),
            'fa fa-facebook' => __( 'Facebook', 'shorts' ),
            'fa fa-facebook-official' => __( 'Facebook Official', 'shorts' ),
            'fa fa-facebook-square' => __( 'Facebook Square', 'shorts' ),
            'fa fa-fast-backward' => __( 'fast-backward', 'shorts' ),
            'fa fa-fast-forward' => __( 'fast-forward', 'shorts' ),
            'fa fa-fax' => __( 'Fax', 'shorts' ),
            'fa fa-female' => __( 'Female', 'shorts' ),
            'fa fa-fighter-jet' => __( 'fighter-jet', 'shorts' ),
            'fa fa-file' => __( 'File', 'shorts' ),
            'fa fa-file-archive-o' => __( 'Archive File Outlined', 'shorts' ),
            'fa fa-file-audio-o' => __( 'Audio File Outlined', 'shorts' ),
            'fa fa-file-code-o' => __( 'Code File Outlined', 'shorts' ),
            'fa fa-file-excel-o' => __( 'Excel File Outlined', 'shorts' ),
            'fa fa-file-image-o' => __( 'Image File Outlined', 'shorts' ),
            'fa fa-file-o' => __( 'File Outlined', 'shorts' ),
            'fa fa-file-pdf-o' => __( 'PDF File Outlined', 'shorts' ),
            'fa fa-file-powerpoint-o' => __( 'Powerpoint File Outlined', 'shorts' ),
            'fa fa-file-text' => __( 'File Text', 'shorts' ),
            'fa fa-file-text-o' => __( 'File Text Outlined', 'shorts' ),
            'fa fa-file-video-o' => __( 'Video File Outlined', 'shorts' ),
            'fa fa-file-word-o' => __( 'Word File Outlined', 'shorts' ),
            'fa fa-files-o' => __( 'Files Outlined', 'shorts' ),
            'fa fa-film' => __( 'Film', 'shorts' ),
            'fa fa-filter' => __( 'Filter', 'shorts' ),
            'fa fa-fire' => __( 'fire', 'shorts' ),
            'fa fa-fire-extinguisher' => __( 'fire-extinguisher', 'shorts' ),
            'fa fa-firefox' => __( 'Firefox', 'shorts' ),
            'fa fa-first-order' => __( 'First Order', 'shorts' ),
            'fa fa-flag' => __( 'flag', 'shorts' ),
            'fa fa-flag-checkered' => __( 'flag-checkered', 'shorts' ),
            'fa fa-flag-o' => __( 'Flag Outlined', 'shorts' ),
            'fa fa-flask' => __( 'Flask', 'shorts' ),
            'fa fa-flickr' => __( 'Flickr', 'shorts' ),
            'fa fa-floppy-o' => __( 'Floppy Outlined', 'shorts' ),
            'fa fa-folder' => __( 'Folder', 'shorts' ),
            'fa fa-folder-o' => __( 'Folder Outlined', 'shorts' ),
            'fa fa-folder-open' => __( 'Folder Open', 'shorts' ),
            'fa fa-folder-open-o' => __( 'Folder Open Outlined', 'shorts' ),
            'fa fa-font' => __( 'font', 'shorts' ),
            'fa fa-fonticons' => __( 'Fonticons', 'shorts' ),
            'fa fa-fort-awesome' => __( 'Fort Awesome', 'shorts' ),
            'fa fa-forumbee' => __( 'Forumbee', 'shorts' ),
            'fa fa-forward' => __( 'forward', 'shorts' ),
            'fa fa-foursquare' => __( 'Foursquare', 'shorts' ),
            'fa fa-frown-o' => __( 'Frown Outlined', 'shorts' ),
            'fa fa-futbol-o' => __( 'Futbol Outlined', 'shorts' ),
            'fa fa-gamepad' => __( 'Gamepad', 'shorts' ),
            'fa fa-gavel' => __( 'Gavel', 'shorts' ),
            'fa fa-gbp' => __( 'GBP', 'shorts' ),
            'fa fa-genderless' => __( 'Genderless', 'shorts' ),
            'fa fa-get-pocket' => __( 'Get Pocket', 'shorts' ),
            'fa fa-gg' => __( 'GG Currency', 'shorts' ),
            'fa fa-gg-circle' => __( 'GG Currency Circle', 'shorts' ),
            'fa fa-gift' => __( 'gift', 'shorts' ),
            'fa fa-git' => __( 'Git', 'shorts' ),
            'fa fa-git-square' => __( 'Git Square', 'shorts' ),
            'fa fa-github' => __( 'GitHub', 'shorts' ),
            'fa fa-github-alt' => __( 'GitHub Alt', 'shorts' ),
            'fa fa-github-square' => __( 'GitHub Square', 'shorts' ),
            'fa fa-gitlab' => __( 'GitLab', 'shorts' ),
            'fa fa-glass' => __( 'Glass', 'shorts' ),
            'fa fa-glide' => __( 'Glide', 'shorts' ),
            'fa fa-glide-g' => __( 'Glide G', 'shorts' ),
            'fa fa-globe' => __( 'Globe', 'shorts' ),
            'fa fa-google' => __( 'Google Logo', 'shorts' ),
            'fa fa-google-plus' => __( 'Google Plus', 'shorts' ),
            'fa fa-google-plus-square' => __( 'Google Plus Square', 'shorts' ),
            'fa fa-google-wallet' => __( 'Google Wallet', 'shorts' ),
            'fa fa-graduation-cap' => __( 'Graduation Cap', 'shorts' ),
            'fa fa-gratipay' => __( 'Gratipay (Gittip)', 'shorts' ),
            'fa fa-h-square' => __( 'H Square', 'shorts' ),
            'fa fa-hacker-news' => __( 'Hacker News', 'shorts' ),
            'fa fa-hand-lizard-o' => __( 'Lizard (Hand)', 'shorts' ),
            'fa fa-hand-o-down' => __( 'Hand Outlined Down', 'shorts' ),
            'fa fa-hand-o-left' => __( 'Hand Outlined Left', 'shorts' ),
            'fa fa-hand-o-right' => __( 'Hand Outlined Right', 'shorts' ),
            'fa fa-hand-o-up' => __( 'Hand Outlined Up', 'shorts' ),
            'fa fa-hand-paper-o' => __( 'Paper (Hand)', 'shorts' ),
            'fa fa-hand-peace-o' => __( 'Hand Peace', 'shorts' ),
            'fa fa-hand-pointer-o' => __( 'Hand Pointer', 'shorts' ),
            'fa fa-hand-rock-o' => __( 'Rock (Hand)', 'shorts' ),
            'fa fa-hand-scissors-o' => __( 'Scissors (Hand)', 'shorts' ),
            'fa fa-hand-spock-o' => __( 'Spock (Hand)', 'shorts' ),
            'fa fa-hashtag' => __( 'Hashtag', 'shorts' ),
            'fa fa-hdd-o' => __( 'HDD', 'shorts' ),
            'fa fa-header' => __( 'header', 'shorts' ),
            'fa fa-headphones' => __( 'headphones', 'shorts' ),
            'fa fa-heart' => __( 'Heart', 'shorts' ),
            'fa fa-heart-o' => __( 'Heart Outlined', 'shorts' ),
            'fa fa-heartbeat' => __( 'Heartbeat', 'shorts' ),
            'fa fa-history' => __( 'History', 'shorts' ),
            'fa fa-home' => __( 'home', 'shorts' ),
            'fa fa-hospital-o' => __( 'hospital Outlined', 'shorts' ),
            'fa fa-hourglass' => __( 'Hourglass', 'shorts' ),
            'fa fa-hourglass-end' => __( 'Hourglass End', 'shorts' ),
            'fa fa-hourglass-half' => __( 'Hourglass Half', 'shorts' ),
            'fa fa-hourglass-o' => __( 'Hourglass Outlined', 'shorts' ),
            'fa fa-hourglass-start' => __( 'Hourglass Start', 'shorts' ),
            'fa fa-houzz' => __( 'Houzz', 'shorts' ),
            'fa fa-html5' => __( 'HTML 5 Logo', 'shorts' ),
            'fa fa-i-cursor' => __( 'I Beam Cursor', 'shorts' ),
            'fa fa-ils' => __( 'Shekel (ILS)', 'shorts' ),
            'fa fa-inbox' => __( 'inbox', 'shorts' ),
            'fa fa-indent' => __( 'Indent', 'shorts' ),
            'fa fa-industry' => __( 'Industry', 'shorts' ),
            'fa fa-info' => __( 'Info', 'shorts' ),
            'fa fa-info-circle' => __( 'Info Circle', 'shorts' ),
            'fa fa-inr' => __( 'Indian Rupee (INR)', 'shorts' ),
            'fa fa-instagram' => __( 'Instagram', 'shorts' ),
            'fa fa-internet-explorer' => __( 'Internet-explorer', 'shorts' ),
            'fa fa-ioxhost' => __( 'ioxhost', 'shorts' ),
            'fa fa-italic' => __( 'italic', 'shorts' ),
            'fa fa-joomla' => __( 'Joomla Logo', 'shorts' ),
            'fa fa-jpy' => __( 'Japanese Yen (JPY)', 'shorts' ),
            'fa fa-jsfiddle' => __( 'jsFiddle', 'shorts' ),
            'fa fa-key' => __( 'key', 'shorts' ),
            'fa fa-keyboard-o' => __( 'Keyboard Outlined', 'shorts' ),
            'fa fa-krw' => __( 'Korean Won (KRW)', 'shorts' ),
            'fa fa-language' => __( 'Language', 'shorts' ),
            'fa fa-laptop' => __( 'Laptop', 'shorts' ),
            'fa fa-lastfm' => __( 'last.fm', 'shorts' ),
            'fa fa-lastfm-square' => __( 'last.fm Square', 'shorts' ),
            'fa fa-leaf' => __( 'leaf', 'shorts' ),
            'fa fa-leanpub' => __( 'Leanpub', 'shorts' ),
            'fa fa-lemon-o' => __( 'Lemon Outlined', 'shorts' ),
            'fa fa-level-down' => __( 'Level Down', 'shorts' ),
            'fa fa-level-up' => __( 'Level Up', 'shorts' ),
            'fa fa-life-ring' => __( 'Life Ring', 'shorts' ),
            'fa fa-lightbulb-o' => __( 'Lightbulb Outlined', 'shorts' ),
            'fa fa-line-chart' => __( 'Line Chart', 'shorts' ),
            'fa fa-link' => __( 'Link', 'shorts' ),
            'fa fa-linkedin' => __( 'LinkedIn', 'shorts' ),
            'fa fa-linkedin-square' => __( 'LinkedIn Square', 'shorts' ),
            'fa fa-linux' => __( 'Linux', 'shorts' ),
            'fa fa-list' => __( 'list', 'shorts' ),
            'fa fa-list-alt' => __( 'list-alt', 'shorts' ),
            'fa fa-list-ol' => __( 'list-ol', 'shorts' ),
            'fa fa-list-ul' => __( 'list-ul', 'shorts' ),
            'fa fa-location-arrow' => __( 'location-arrow', 'shorts' ),
            'fa fa-lock' => __( 'lock', 'shorts' ),
            'fa fa-long-arrow-down' => __( 'Long Arrow Down', 'shorts' ),
            'fa fa-long-arrow-left' => __( 'Long Arrow Left', 'shorts' ),
            'fa fa-long-arrow-right' => __( 'Long Arrow Right', 'shorts' ),
            'fa fa-long-arrow-up' => __( 'Long Arrow Up', 'shorts' ),
            'fa fa-low-vision' => __( 'Low Vision', 'shorts' ),
            'fa fa-magic' => __( 'magic', 'shorts' ),
            'fa fa-magnet' => __( 'magnet', 'shorts' ),
            'fa fa-male' => __( 'Male', 'shorts' ),
            'fa fa-map' => __( 'Map', 'shorts' ),
            'fa fa-map-marker' => __( 'map-marker', 'shorts' ),
            'fa fa-map-o' => __( 'Map Outline', 'shorts' ),
            'fa fa-map-pin' => __( 'Map Pin', 'shorts' ),
            'fa fa-map-signs' => __( 'Map Signs', 'shorts' ),
            'fa fa-mars' => __( 'Mars', 'shorts' ),
            'fa fa-mars-double' => __( 'Mars Double', 'shorts' ),
            'fa fa-mars-stroke' => __( 'Mars Stroke', 'shorts' ),
            'fa fa-mars-stroke-h' => __( 'Mars Stroke Horizontal', 'shorts' ),
            'fa fa-mars-stroke-v' => __( 'Mars Stroke Vertical', 'shorts' ),
            'fa fa-maxcdn' => __( 'MaxCDN', 'shorts' ),
            'fa fa-meanpath' => __( 'meanpath', 'shorts' ),
            'fa fa-medium' => __( 'Medium', 'shorts' ),
            'fa fa-medkit' => __( 'medkit', 'shorts' ),
            'fa fa-meh-o' => __( 'Meh Outlined', 'shorts' ),
            'fa fa-mercury' => __( 'Mercury', 'shorts' ),
            'fa fa-microphone' => __( 'microphone', 'shorts' ),
            'fa fa-microphone-slash' => __( 'Microphone Slash', 'shorts' ),
            'fa fa-minus' => __( 'minus', 'shorts' ),
            'fa fa-minus-circle' => __( 'Minus Circle', 'shorts' ),
            'fa fa-minus-square' => __( 'Minus Square', 'shorts' ),
            'fa fa-minus-square-o' => __( 'Minus Square Outlined', 'shorts' ),
            'fa fa-mixcloud' => __( 'Mixcloud', 'shorts' ),
            'fa fa-mobile' => __( 'Mobile Phone', 'shorts' ),
            'fa fa-modx' => __( 'MODX', 'shorts' ),
            'fa fa-money' => __( 'Money', 'shorts' ),
            'fa fa-moon-o' => __( 'Moon Outlined', 'shorts' ),
            'fa fa-motorcycle' => __( 'Motorcycle', 'shorts' ),
            'fa fa-mouse-pointer' => __( 'Mouse Pointer', 'shorts' ),
            'fa fa-music' => __( 'Music', 'shorts' ),
            'fa fa-neuter' => __( 'Neuter', 'shorts' ),
            'fa fa-newspaper-o' => __( 'Newspaper Outlined', 'shorts' ),
            'fa fa-object-group' => __( 'Object Group', 'shorts' ),
            'fa fa-object-ungroup' => __( 'Object Ungroup', 'shorts' ),
            'fa fa-odnoklassniki' => __( 'Odnoklassniki', 'shorts' ),
            'fa fa-odnoklassniki-square' => __( 'Odnoklassniki Square', 'shorts' ),
            'fa fa-opencart' => __( 'OpenCart', 'shorts' ),
            'fa fa-openid' => __( 'OpenID', 'shorts' ),
            'fa fa-opera' => __( 'Opera', 'shorts' ),
            'fa fa-optin-monster' => __( 'Optin Monster', 'shorts' ),
            'fa fa-outdent' => __( 'Outdent', 'shorts' ),
            'fa fa-pagelines' => __( 'Pagelines', 'shorts' ),
            'fa fa-paint-brush' => __( 'Paint Brush', 'shorts' ),
            'fa fa-paper-plane' => __( 'Paper Plane', 'shorts' ),
            'fa fa-paper-plane-o' => __( 'Paper Plane Outlined', 'shorts' ),
            'fa fa-paperclip' => __( 'Paperclip', 'shorts' ),
            'fa fa-paragraph' => __( 'paragraph', 'shorts' ),
            'fa fa-pause' => __( 'pause', 'shorts' ),
            'fa fa-pause-circle' => __( 'Pause Circle', 'shorts' ),
            'fa fa-pause-circle-o' => __( 'Pause Circle Outlined', 'shorts' ),
            'fa fa-paw' => __( 'Paw', 'shorts' ),
            'fa fa-paypal' => __( 'Paypal', 'shorts' ),
            'fa fa-pencil' => __( 'pencil', 'shorts' ),
            'fa fa-pencil-square' => __( 'Pencil Square', 'shorts' ),
            'fa fa-pencil-square-o' => __( 'Pencil Square Outlined', 'shorts' ),
            'fa fa-percent' => __( 'Percent', 'shorts' ),
            'fa fa-phone' => __( 'Phone', 'shorts' ),
            'fa fa-phone-square' => __( 'Phone Square', 'shorts' ),
            'fa fa-picture-o' => __( 'Picture Outlined', 'shorts' ),
            'fa fa-pie-chart' => __( 'Pie Chart', 'shorts' ),
            'fa fa-pied-piper' => __( 'Pied Piper Logo', 'shorts' ),
            'fa fa-pied-piper-alt' => __( 'Pied Piper Alternate Logo', 'shorts' ),
            'fa fa-pied-piper-pp' => __( 'Pied Piper PP Logo (Old)', 'shorts' ),
            'fa fa-pinterest' => __( 'Pinterest', 'shorts' ),
            'fa fa-pinterest-p' => __( 'Pinterest P', 'shorts' ),
            'fa fa-pinterest-square' => __( 'Pinterest Square', 'shorts' ),
            'fa fa-plane' => __( 'plane', 'shorts' ),
            'fa fa-play' => __( 'play', 'shorts' ),
            'fa fa-play-circle' => __( 'Play Circle', 'shorts' ),
            'fa fa-play-circle-o' => __( 'Play Circle Outlined', 'shorts' ),
            'fa fa-plug' => __( 'Plug', 'shorts' ),
            'fa fa-plus' => __( 'plus', 'shorts' ),
            'fa fa-plus-circle' => __( 'Plus Circle', 'shorts' ),
            'fa fa-plus-square' => __( 'Plus Square', 'shorts' ),
            'fa fa-plus-square-o' => __( 'Plus Square Outlined', 'shorts' ),
            'fa fa-power-off' => __( 'Power Off', 'shorts' ),
            'fa fa-print' => __( 'print', 'shorts' ),
            'fa fa-product-hunt' => __( 'Product Hunt', 'shorts' ),
            'fa fa-puzzle-piece' => __( 'Puzzle Piece', 'shorts' ),
            'fa fa-qq' => __( 'QQ', 'shorts' ),
            'fa fa-qrcode' => __( 'qrcode', 'shorts' ),
            'fa fa-question' => __( 'Question', 'shorts' ),
            'fa fa-question-circle' => __( 'Question Circle', 'shorts' ),
            'fa fa-question-circle-o' => __( 'Question Circle Outlined', 'shorts' ),
            'fa fa-quote-left' => __( 'quote-left', 'shorts' ),
            'fa fa-quote-right' => __( 'quote-right', 'shorts' ),
            'fa fa-random' => __( 'random', 'shorts' ),
            'fa fa-rebel' => __( 'Rebel Alliance', 'shorts' ),
            'fa fa-recycle' => __( 'Recycle', 'shorts' ),
            'fa fa-reddit' => __( 'reddit Logo', 'shorts' ),
            'fa fa-reddit-alien' => __( 'reddit Alien', 'shorts' ),
            'fa fa-reddit-square' => __( 'reddit Square', 'shorts' ),
            'fa fa-refresh' => __( 'refresh', 'shorts' ),
            'fa fa-registered' => __( 'Registered Trademark', 'shorts' ),
            'fa fa-renren' => __( 'Renren', 'shorts' ),
            'fa fa-repeat' => __( 'Repeat', 'shorts' ),
            'fa fa-reply' => __( 'Reply', 'shorts' ),
            'fa fa-reply-all' => __( 'reply-all', 'shorts' ),
            'fa fa-retweet' => __( 'retweet', 'shorts' ),
            'fa fa-road' => __( 'road', 'shorts' ),
            'fa fa-rocket' => __( 'rocket', 'shorts' ),
            'fa fa-rss' => __( 'rss', 'shorts' ),
            'fa fa-rss-square' => __( 'RSS Square', 'shorts' ),
            'fa fa-rub' => __( 'Russian Ruble (RUB)', 'shorts' ),
            'fa fa-safari' => __( 'Safari', 'shorts' ),
            'fa fa-scissors' => __( 'Scissors', 'shorts' ),
            'fa fa-scribd' => __( 'Scribd', 'shorts' ),
            'fa fa-search' => __( 'Search', 'shorts' ),
            'fa fa-search-minus' => __( 'Search Minus', 'shorts' ),
            'fa fa-search-plus' => __( 'Search Plus', 'shorts' ),
            'fa fa-sellsy' => __( 'Sellsy', 'shorts' ),
            'fa fa-server' => __( 'Server', 'shorts' ),
            'fa fa-share' => __( 'Share', 'shorts' ),
            'fa fa-share-alt' => __( 'Share Alt', 'shorts' ),
            'fa fa-share-alt-square' => __( 'Share Alt Square', 'shorts' ),
            'fa fa-share-square' => __( 'Share Square', 'shorts' ),
            'fa fa-share-square-o' => __( 'Share Square Outlined', 'shorts' ),
            'fa fa-shield' => __( 'shield', 'shorts' ),
            'fa fa-ship' => __( 'Ship', 'shorts' ),
            'fa fa-shirtsinbulk' => __( 'Shirts in Bulk', 'shorts' ),
            'fa fa-shopping-bag' => __( 'Shopping Bag', 'shorts' ),
            'fa fa-shopping-basket' => __( 'Shopping Basket', 'shorts' ),
            'fa fa-shopping-cart' => __( 'shopping-cart', 'shorts' ),
            'fa fa-sign-in' => __( 'Sign In', 'shorts' ),
            'fa fa-sign-language' => __( 'Sign Language', 'shorts' ),
            'fa fa-sign-out' => __( 'Sign Out', 'shorts' ),
            'fa fa-signal' => __( 'signal', 'shorts' ),
            'fa fa-simplybuilt' => __( 'SimplyBuilt', 'shorts' ),
            'fa fa-sitemap' => __( 'Sitemap', 'shorts' ),
            'fa fa-skyatlas' => __( 'skyatlas', 'shorts' ),
            'fa fa-skype' => __( 'Skype', 'shorts' ),
            'fa fa-slack' => __( 'Slack Logo', 'shorts' ),
            'fa fa-sliders' => __( 'Sliders', 'shorts' ),
            'fa fa-slideshare' => __( 'Slideshare', 'shorts' ),
            'fa fa-smile-o' => __( 'Smile Outlined', 'shorts' ),
            'fa fa-snapchat' => __( 'Snapchat', 'shorts' ),
            'fa fa-snapchat-ghost' => __( 'Snapchat Ghost', 'shorts' ),
            'fa fa-snapchat-square' => __( 'Snapchat Square', 'shorts' ),
            'fa fa-sort' => __( 'Sort', 'shorts' ),
            'fa fa-sort-alpha-asc' => __( 'Sort Alpha Ascending', 'shorts' ),
            'fa fa-sort-alpha-desc' => __( 'Sort Alpha Descending', 'shorts' ),
            'fa fa-sort-amount-asc' => __( 'Sort Amount Ascending', 'shorts' ),
            'fa fa-sort-amount-desc' => __( 'Sort Amount Descending', 'shorts' ),
            'fa fa-sort-asc' => __( 'Sort Ascending', 'shorts' ),
            'fa fa-sort-desc' => __( 'Sort Descending', 'shorts' ),
            'fa fa-sort-numeric-asc' => __( 'Sort Numeric Ascending', 'shorts' ),
            'fa fa-sort-numeric-desc' => __( 'Sort Numeric Descending', 'shorts' ),
            'fa fa-soundcloud' => __( 'SoundCloud', 'shorts' ),
            'fa fa-space-shuttle' => __( 'Space Shuttle', 'shorts' ),
            'fa fa-spinner' => __( 'Spinner', 'shorts' ),
            'fa fa-spoon' => __( 'spoon', 'shorts' ),
            'fa fa-spotify' => __( 'Spotify', 'shorts' ),
            'fa fa-square' => __( 'Square', 'shorts' ),
            'fa fa-square-o' => __( 'Square Outlined', 'shorts' ),
            'fa fa-stack-exchange' => __( 'Stack Exchange', 'shorts' ),
            'fa fa-stack-overflow' => __( 'Stack Overflow', 'shorts' ),
            'fa fa-star' => __( 'Star', 'shorts' ),
            'fa fa-star-half' => __( 'star-half', 'shorts' ),
            'fa fa-star-half-o' => __( 'Star Half Outlined', 'shorts' ),
            'fa fa-star-o' => __( 'Star Outlined', 'shorts' ),
            'fa fa-steam' => __( 'Steam', 'shorts' ),
            'fa fa-steam-square' => __( 'Steam Square', 'shorts' ),
            'fa fa-step-backward' => __( 'step-backward', 'shorts' ),
            'fa fa-step-forward' => __( 'step-forward', 'shorts' ),
            'fa fa-stethoscope' => __( 'Stethoscope', 'shorts' ),
            'fa fa-sticky-note' => __( 'Sticky Note', 'shorts' ),
            'fa fa-sticky-note-o' => __( 'Sticky Note Outlined', 'shorts' ),
            'fa fa-stop' => __( 'stop', 'shorts' ),
            'fa fa-stop-circle' => __( 'Stop Circle', 'shorts' ),
            'fa fa-stop-circle-o' => __( 'Stop Circle Outlined', 'shorts' ),
            'fa fa-street-view' => __( 'Street View', 'shorts' ),
            'fa fa-strikethrough' => __( 'Strikethrough', 'shorts' ),
            'fa fa-stumbleupon' => __( 'StumbleUpon Logo', 'shorts' ),
            'fa fa-stumbleupon-circle' => __( 'StumbleUpon Circle', 'shorts' ),
            'fa fa-subscript' => __( 'subscript', 'shorts' ),
            'fa fa-subway' => __( 'Subway', 'shorts' ),
            'fa fa-suitcase' => __( 'Suitcase', 'shorts' ),
            'fa fa-sun-o' => __( 'Sun Outlined', 'shorts' ),
            'fa fa-superscript' => __( 'superscript', 'shorts' ),
            'fa fa-table' => __( 'table', 'shorts' ),
            'fa fa-tablet' => __( 'tablet', 'shorts' ),
            'fa fa-tachometer' => __( 'Tachometer', 'shorts' ),
            'fa fa-tag' => __( 'tag', 'shorts' ),
            'fa fa-tags' => __( 'tags', 'shorts' ),
            'fa fa-tasks' => __( 'Tasks', 'shorts' ),
            'fa fa-taxi' => __( 'Taxi', 'shorts' ),
            'fa fa-television' => __( 'Television', 'shorts' ),
            'fa fa-tencent-weibo' => __( 'Tencent Weibo', 'shorts' ),
            'fa fa-terminal' => __( 'Terminal', 'shorts' ),
            'fa fa-text-height' => __( 'text-height', 'shorts' ),
            'fa fa-text-width' => __( 'text-width', 'shorts' ),
            'fa fa-th' => __( 'th', 'shorts' ),
            'fa fa-th-large' => __( 'th-large', 'shorts' ),
            'fa fa-th-list' => __( 'th-list', 'shorts' ),
            'fa fa-themeisle' => __( 'ThemeIsle', 'shorts' ),
            'fa fa-thumb-tack' => __( 'Thumb Tack', 'shorts' ),
            'fa fa-thumbs-down' => __( 'thumbs-down', 'shorts' ),
            'fa fa-thumbs-o-down' => __( 'Thumbs Down Outlined', 'shorts' ),
            'fa fa-thumbs-o-up' => __( 'Thumbs Up Outlined', 'shorts' ),
            'fa fa-thumbs-up' => __( 'thumbs-up', 'shorts' ),
            'fa fa-ticket' => __( 'Ticket', 'shorts' ),
            'fa fa-times' => __( 'Times', 'shorts' ),
            'fa fa-times-circle' => __( 'Times Circle', 'shorts' ),
            'fa fa-times-circle-o' => __( 'Times Circle Outlined', 'shorts' ),
            'fa fa-tint' => __( 'tint', 'shorts' ),
            'fa fa-toggle-off' => __( 'Toggle Off', 'shorts' ),
            'fa fa-toggle-on' => __( 'Toggle On', 'shorts' ),
            'fa fa-trademark' => __( 'Trademark', 'shorts' ),
            'fa fa-train' => __( 'Train', 'shorts' ),
            'fa fa-transgender' => __( 'Transgender', 'shorts' ),
            'fa fa-transgender-alt' => __( 'Transgender Alt', 'shorts' ),
            'fa fa-trash' => __( 'Trash', 'shorts' ),
            'fa fa-trash-o' => __( 'Trash Outlined', 'shorts' ),
            'fa fa-tree' => __( 'Tree', 'shorts' ),
            'fa fa-trello' => __( 'Trello', 'shorts' ),
            'fa fa-tripadvisor' => __( 'TripAdvisor', 'shorts' ),
            'fa fa-trophy' => __( 'trophy', 'shorts' ),
            'fa fa-truck' => __( 'truck', 'shorts' ),
            'fa fa-try' => __( 'Turkish Lira (TRY)', 'shorts' ),
            'fa fa-tty' => __( 'TTY', 'shorts' ),
            'fa fa-tumblr' => __( 'Tumblr', 'shorts' ),
            'fa fa-tumblr-square' => __( 'Tumblr Square', 'shorts' ),
            'fa fa-twitch' => __( 'Twitch', 'shorts' ),
            'fa fa-twitter' => __( 'Twitter', 'shorts' ),
            'fa fa-twitter-square' => __( 'Twitter Square', 'shorts' ),
            'fa fa-umbrella' => __( 'Umbrella', 'shorts' ),
            'fa fa-underline' => __( 'Underline', 'shorts' ),
            'fa fa-undo' => __( 'Undo', 'shorts' ),
            'fa fa-universal-access' => __( 'Universal Access', 'shorts' ),
            'fa fa-university' => __( 'University', 'shorts' ),
            'fa fa-unlock' => __( 'unlock', 'shorts' ),
            'fa fa-unlock-alt' => __( 'Unlock Alt', 'shorts' ),
            'fa fa-upload' => __( 'Upload', 'shorts' ),
            'fa fa-usb' => __( 'USB', 'shorts' ),
            'fa fa-usd' => __( 'US Dollar', 'shorts' ),
            'fa fa-user' => __( 'User', 'shorts' ),
            'fa fa-user-md' => __( 'user-md', 'shorts' ),
            'fa fa-user-plus' => __( 'Add User', 'shorts' ),
            'fa fa-user-secret' => __( 'User Secret', 'shorts' ),
            'fa fa-user-times' => __( 'Remove User', 'shorts' ),
            'fa fa-users' => __( 'Users', 'shorts' ),
            'fa fa-venus' => __( 'Venus', 'shorts' ),
            'fa fa-venus-double' => __( 'Venus Double', 'shorts' ),
            'fa fa-venus-mars' => __( 'Venus Mars', 'shorts' ),
            'fa fa-viacoin' => __( 'Viacoin', 'shorts' ),
            'fa fa-viadeo' => __( 'Viadeo', 'shorts' ),
            'fa fa-viadeo-square' => __( 'Viadeo Square', 'shorts' ),
            'fa fa-video-camera' => __( 'Video Camera', 'shorts' ),
            'fa fa-vimeo' => __( 'Vimeo', 'shorts' ),
            'fa fa-vimeo-square' => __( 'Vimeo Square', 'shorts' ),
            'fa fa-vine' => __( 'Vine', 'shorts' ),
            'fa fa-vk' => __( 'VK', 'shorts' ),
            'fa fa-volume-control-phone' => __( 'Volume Control Phone', 'shorts' ),
            'fa fa-volume-down' => __( 'volume-down', 'shorts' ),
            'fa fa-volume-off' => __( 'volume-off', 'shorts' ),
            'fa fa-volume-up' => __( 'volume-up', 'shorts' ),
            'fa fa-weibo' => __( 'Weibo', 'shorts' ),
            'fa fa-weixin' => __( 'Weixin (WeChat)', 'shorts' ),
            'fa fa-whatsapp' => __( 'What\'s App', 'shorts' ),
            'fa fa-wheelchair' => __( 'Wheelchair', 'shorts' ),
            'fa fa-wheelchair-alt' => __( 'Wheelchair Alt', 'shorts' ),
            'fa fa-wifi' => __( 'WiFi', 'shorts' ),
            'fa fa-wikipedia-w' => __( 'Wikipedia W', 'shorts' ),
            'fa fa-windows' => __( 'Windows', 'shorts' ),
            'fa fa-wordpress' => __( 'WordPress Logo', 'shorts' ),
            'fa fa-wpbeginner' => __( 'WPBeginner', 'shorts' ),
            'fa fa-wpforms' => __( 'WPForms', 'shorts' ),
            'fa fa-wrench' => __( 'Wrench', 'shorts' ),
            'fa fa-xing' => __( 'Xing', 'shorts' ),
            'fa fa-xing-square' => __( 'Xing Square', 'shorts' ),
            'fa fa-y-combinator' => __( 'Y Combinator', 'shorts' ),
            'fa fa-yahoo' => __( 'Yahoo Logo', 'shorts' ),
            'fa fa-yelp' => __( 'Yelp', 'shorts' ),
            'fa fa-yoast' => __( 'Yoast', 'shorts' ),
            'fa fa-youtube' => __( 'YouTube', 'shorts' ),
            'fa fa-youtube-play' => __( 'YouTube Play', 'shorts' ),
            'fa fa-youtube-square' => __( 'YouTube Square', 'shorts' )
        ];

        return apply_filters( 'imacon/icons', $icons );

    }

}
