<?php
/**
* Imacons Defaults
*
* @package Imacon
*/

namespace Lambry\Imacon;

defined( 'ABSPATH' ) || exit;

/* Defaults Class */
class Defaults {

    /**  
    * Placeholder
    *
    * @access public
    * @return string $placeholder
    */
    public static function placeholder() {

        $placeholder = 'data:image/svg+xml;base64,PHN2ZyBmaWxsPSIjOTk5IiB3aWR0aD0iNzUiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDU1MC44MDEgNTUwLjgiPjxwYXRoIGQ9Ik01MTUuODI4IDYxLjJIMzQuOTcyQzE1LjY2IDYxLjIgMCA3Ni44NiAwIDk2LjE3M1Y0NTQuNjNjMCAxOS4zMTIgMTUuNjYgMzQuOTcgMzQuOTcyIDM0Ljk3aDQ4MC44NTZjMTkuMzE0IDAgMzQuOTczLTE1LjY1OCAzNC45NzMtMzQuOTdWOTYuMTdjMC0xOS4zMTMtMTUuNjU3LTM0Ljk3LTM0Ljk3Mi0zNC45N3ptMCAzNC45NzJWMzUwLjUxbC02OC45Mi02Mi42NmMtMTAuMzYtOS40MTYtMjYuMjktOS4wNC0zNi4xODYuODY2bC02OS43NTIgNjkuNzRMMjAzLjQzOCAxOTQuMThjLTEwLjM5Ni0xMi40MTYtMjkuNDM4LTEyLjUzOC0zOS45OS0uMjcyTDM0Ljk3MiAzNDMuMjE4Vjk2LjE3M2g0ODAuODU2em0tMTQ4LjYyNyA5MS44YzAtMjYuNTYgMjEuNTI0LTQ4LjA4NiA0OC4wODUtNDguMDg2IDI2LjU2MiAwIDQ4LjA4NiAyMS41MjUgNDguMDg2IDQ4LjA4NiAwIDI2LjU2LTIxLjUyMiA0OC4wODUtNDguMDg1IDQ4LjA4NS0yNi41NiAwLTQ4LjA4NC0yMS41MjQtNDguMDg0LTQ4LjA4NXoiPjwvcGF0aD48L3N2Zz4=';

        return apply_filters( 'imacon/placeholder', $placeholder );

    }

    /**
    * Fields
    *
    * @access public
    * @return array $fields
    */
    public static function fields() {

        $fields = array_map( function( $field ) {
            return ( isset( $field['label'] ) ) ? $field['label']  : key( $field );
        }, Setup::fields() );

        return apply_filters( 'imacon/fields', $fields );

    }

    /**
    * Sizes
    *
    * @access public
    * @return array $sizes
    */
    public static function sizes() {

        $sizes = [];
        $sizes_list = get_intermediate_image_sizes();

        foreach ( $sizes_list as $size ) {
            $sizes[$size] = ucwords( str_replace( '_', ' ', $size ) );
        }
        $sizes['full'] = 'Full';

        return apply_filters( 'imacon/sizes', $sizes );

    }

    /**
    * Icons
    *
    * @access public
    * @return array $icons
    */
    public static function icons() {

        $icons = [
            'fa fa-500px' => __( '500px', 'imacon' ),
            'fa fa-adjust' => __( 'Adjust', 'imacon' ),
            'fa fa-adn' => __( 'Adn', 'imacon' ),
            'fa fa-align-center' => __( 'Align Center', 'imacon' ),
            'fa fa-align-justify' => __( 'Align Justify', 'imacon' ),
            'fa fa-align-left' => __( 'Align Left', 'imacon' ),
            'fa fa-align-right' => __( 'Align Right', 'imacon' ),
            'fa fa-amazon' => __( 'Amazon', 'imacon' ),
            'fa fa-ambulance' => __( 'Ambulance', 'imacon' ),
            'fa fa-anchor' => __( 'Anchor', 'imacon' ),
            'fa fa-android' => __( 'Android', 'imacon' ),
            'fa fa-angellist' => __( 'Angellist', 'imacon' ),
            'fa fa-angle-double-down' => __( 'Angle Double Down', 'imacon' ),
            'fa fa-angle-double-left' => __( 'Angle Double Left', 'imacon' ),
            'fa fa-angle-double-right' => __( 'Angle Double Right', 'imacon' ),
            'fa fa-angle-double-up' => __( 'Angle Double Up', 'imacon' ),
            'fa fa-angle-down' => __( 'Angle Down', 'imacon' ),
            'fa fa-angle-left' => __( 'Angle Left', 'imacon' ),
            'fa fa-angle-right' => __( 'Angle Right', 'imacon' ),
            'fa fa-angle-up' => __( 'Angle Up', 'imacon' ),
            'fa fa-apple' => __( 'Apple', 'imacon' ),
            'fa fa-archive' => __( 'Archive', 'imacon' ),
            'fa fa-area-chart' => __( 'Area Chart', 'imacon' ),
            'fa fa-arrow-circle-down' => __( 'Arrow Circle Down', 'imacon' ),
            'fa fa-arrow-circle-left' => __( 'Arrow Circle Left', 'imacon' ),
            'fa fa-arrow-circle-o-down' => __( 'Arrow Circle O Down', 'imacon' ),
            'fa fa-arrow-circle-o-left' => __( 'Arrow Circle O Left', 'imacon' ),
            'fa fa-arrow-circle-o-right' => __( 'Arrow Circle O Right', 'imacon' ),
            'fa fa-arrow-circle-o-up' => __( 'Arrow Circle O Up', 'imacon' ),
            'fa fa-arrow-circle-right' => __( 'Arrow Circle Right', 'imacon' ),
            'fa fa-arrow-circle-up' => __( 'Arrow Circle Up', 'imacon' ),
            'fa fa-arrow-down' => __( 'Arrow Down', 'imacon' ),
            'fa fa-arrow-left' => __( 'Arrow Left', 'imacon' ),
            'fa fa-arrow-right' => __( 'Arrow Right', 'imacon' ),
            'fa fa-arrow-up' => __( 'Arrow Up', 'imacon' ),
            'fa fa-arrows' => __( 'Arrows', 'imacon' ),
            'fa fa-arrows-alt' => __( 'Arrows Alt', 'imacon' ),
            'fa fa-arrows-h' => __( 'Arrows H', 'imacon' ),
            'fa fa-arrows-v' => __( 'Arrows V', 'imacon' ),
            'fa fa-asterisk' => __( 'Asterisk', 'imacon' ),
            'fa fa-at' => __( 'At', 'imacon' ),
            'fa fa-backward' => __( 'Backward', 'imacon' ),
            'fa fa-balance-scale' => __( 'Balance Scale', 'imacon' ),
            'fa fa-ban' => __( 'Ban', 'imacon' ),
            'fa fa-bar-chart' => __( 'Bar Chart', 'imacon' ),
            'fa fa-barcode' => __( 'Barcode', 'imacon' ),
            'fa fa-bars' => __( 'Bars', 'imacon' ),
            'fa fa-battery-empty' => __( 'Battery Empty', 'imacon' ),
            'fa fa-battery-full' => __( 'Battery Full', 'imacon' ),
            'fa fa-battery-half' => __( 'Battery Half', 'imacon' ),
            'fa fa-battery-quarter' => __( 'Battery Quarter', 'imacon' ),
            'fa fa-battery-three-quarters' => __( 'Battery Three Quarters', 'imacon' ),
            'fa fa-bed' => __( 'Bed', 'imacon' ),
            'fa fa-beer' => __( 'Beer', 'imacon' ),
            'fa fa-behance' => __( 'Behance', 'imacon' ),
            'fa fa-behance-square' => __( 'Behance Square', 'imacon' ),
            'fa fa-bell' => __( 'Bell', 'imacon' ),
            'fa fa-bell-o' => __( 'Bell O', 'imacon' ),
            'fa fa-bell-slash' => __( 'Bell Slash', 'imacon' ),
            'fa fa-bell-slash-o' => __( 'Bell Slash O', 'imacon' ),
            'fa fa-bicycle' => __( 'Bicycle', 'imacon' ),
            'fa fa-binoculars' => __( 'Binoculars', 'imacon' ),
            'fa fa-birthday-cake' => __( 'Birthday Cake', 'imacon' ),
            'fa fa-bitbucket' => __( 'Bitbucket', 'imacon' ),
            'fa fa-bitbucket-square' => __( 'Bitbucket Square', 'imacon' ),
            'fa fa-black-tie' => __( 'Black Tie', 'imacon' ),
            'fa fa-bold' => __( 'Bold', 'imacon' ),
            'fa fa-bolt' => __( 'Bolt', 'imacon' ),
            'fa fa-bomb' => __( 'Bomb', 'imacon' ),
            'fa fa-book' => __( 'Book', 'imacon' ),
            'fa fa-bookmark' => __( 'Bookmark', 'imacon' ),
            'fa fa-bookmark-o' => __( 'Bookmark O', 'imacon' ),
            'fa fa-briefcase' => __( 'Briefcase', 'imacon' ),
            'fa fa-btc' => __( 'Btc', 'imacon' ),
            'fa fa-bug' => __( 'Bug', 'imacon' ),
            'fa fa-building' => __( 'Building', 'imacon' ),
            'fa fa-building-o' => __( 'Building O', 'imacon' ),
            'fa fa-bullhorn' => __( 'Bullhorn', 'imacon' ),
            'fa fa-bullseye' => __( 'Bullseye', 'imacon' ),
            'fa fa-bus' => __( 'Bus', 'imacon' ),
            'fa fa-buysellads' => __( 'Buysellads', 'imacon' ),
            'fa fa-calculator' => __( 'Calculator', 'imacon' ),
            'fa fa-calendar' => __( 'Calendar', 'imacon' ),
            'fa fa-calendar-check-o' => __( 'Calendar Check O', 'imacon' ),
            'fa fa-calendar-minus-o' => __( 'Calendar Minus O', 'imacon' ),
            'fa fa-calendar-o' => __( 'Calendar O', 'imacon' ),
            'fa fa-calendar-plus-o' => __( 'Calendar Plus O', 'imacon' ),
            'fa fa-calendar-times-o' => __( 'Calendar Times O', 'imacon' ),
            'fa fa-camera' => __( 'Camera', 'imacon' ),
            'fa fa-camera-retro' => __( 'Camera Retro', 'imacon' ),
            'fa fa-car' => __( 'Car', 'imacon' ),
            'fa fa-caret-down' => __( 'Caret Down', 'imacon' ),
            'fa fa-caret-left' => __( 'Caret Left', 'imacon' ),
            'fa fa-caret-right' => __( 'Caret Right', 'imacon' ),
            'fa fa-caret-square-o-down' => __( 'Caret Square O Down', 'imacon' ),
            'fa fa-caret-square-o-left' => __( 'Caret Square O Left', 'imacon' ),
            'fa fa-caret-square-o-right' => __( 'Caret Square O Right', 'imacon' ),
            'fa fa-caret-square-o-up' => __( 'Caret Square O Up', 'imacon' ),
            'fa fa-caret-up' => __( 'Caret Up', 'imacon' ),
            'fa fa-cart-arrow-down' => __( 'Cart Arrow Down', 'imacon' ),
            'fa fa-cart-plus' => __( 'Cart Plus', 'imacon' ),
            'fa fa-cc' => __( 'Cc', 'imacon' ),
            'fa fa-cc-amex' => __( 'Cc Amex', 'imacon' ),
            'fa fa-cc-diners-club' => __( 'Cc Diners Club', 'imacon' ),
            'fa fa-cc-discover' => __( 'Cc Discover', 'imacon' ),
            'fa fa-cc-jcb' => __( 'Cc Jcb', 'imacon' ),
            'fa fa-cc-mastercard' => __( 'Cc Mastercard', 'imacon' ),
            'fa fa-cc-paypal' => __( 'Cc Paypal', 'imacon' ),
            'fa fa-cc-stripe' => __( 'Cc Stripe', 'imacon' ),
            'fa fa-cc-visa' => __( 'Cc Visa', 'imacon' ),
            'fa fa-certificate' => __( 'Certificate', 'imacon' ),
            'fa fa-chain-broken' => __( 'Chain Broken', 'imacon' ),
            'fa fa-check' => __( 'Check', 'imacon' ),
            'fa fa-check-circle' => __( 'Check Circle', 'imacon' ),
            'fa fa-check-circle-o' => __( 'Check Circle O', 'imacon' ),
            'fa fa-check-square' => __( 'Check Square', 'imacon' ),
            'fa fa-check-square-o' => __( 'Check Square O', 'imacon' ),
            'fa fa-chevron-circle-down' => __( 'Chevron Circle Down', 'imacon' ),
            'fa fa-chevron-circle-left' => __( 'Chevron Circle Left', 'imacon' ),
            'fa fa-chevron-circle-right' => __( 'Chevron Circle Right', 'imacon' ),
            'fa fa-chevron-circle-up' => __( 'Chevron Circle Up', 'imacon' ),
            'fa fa-chevron-down' => __( 'Chevron Down', 'imacon' ),
            'fa fa-chevron-left' => __( 'Chevron Left', 'imacon' ),
            'fa fa-chevron-right' => __( 'Chevron Right', 'imacon' ),
            'fa fa-chevron-up' => __( 'Chevron Up', 'imacon' ),
            'fa fa-child' => __( 'Child', 'imacon' ),
            'fa fa-chrome' => __( 'Chrome', 'imacon' ),
            'fa fa-circle' => __( 'Circle', 'imacon' ),
            'fa fa-circle-o' => __( 'Circle O', 'imacon' ),
            'fa fa-circle-o-notch' => __( 'Circle O Notch', 'imacon' ),
            'fa fa-circle-thin' => __( 'Circle Thin', 'imacon' ),
            'fa fa-clipboard' => __( 'Clipboard', 'imacon' ),
            'fa fa-clock-o' => __( 'Clock O', 'imacon' ),
            'fa fa-clone' => __( 'Clone', 'imacon' ),
            'fa fa-cloud' => __( 'Cloud', 'imacon' ),
            'fa fa-cloud-download' => __( 'Cloud Download', 'imacon' ),
            'fa fa-cloud-upload' => __( 'Cloud Upload', 'imacon' ),
            'fa fa-code' => __( 'Code', 'imacon' ),
            'fa fa-code-fork' => __( 'Code Fork', 'imacon' ),
            'fa fa-codepen' => __( 'Codepen', 'imacon' ),
            'fa fa-coffee' => __( 'Coffee', 'imacon' ),
            'fa fa-cog' => __( 'Cog', 'imacon' ),
            'fa fa-cogs' => __( 'Cogs', 'imacon' ),
            'fa fa-columns' => __( 'Columns', 'imacon' ),
            'fa fa-comment' => __( 'Comment', 'imacon' ),
            'fa fa-comment-o' => __( 'Comment O', 'imacon' ),
            'fa fa-commenting' => __( 'Commenting', 'imacon' ),
            'fa fa-commenting-o' => __( 'Commenting O', 'imacon' ),
            'fa fa-comments' => __( 'Comments', 'imacon' ),
            'fa fa-comments-o' => __( 'Comments O', 'imacon' ),
            'fa fa-compass' => __( 'Compass', 'imacon' ),
            'fa fa-compress' => __( 'Compress', 'imacon' ),
            'fa fa-connectdevelop' => __( 'Connectdevelop', 'imacon' ),
            'fa fa-contao' => __( 'Contao', 'imacon' ),
            'fa fa-copyright' => __( 'Copyright', 'imacon' ),
            'fa fa-creative-commons' => __( 'Creative Commons', 'imacon' ),
            'fa fa-credit-card' => __( 'Credit Card', 'imacon' ),
            'fa fa-crop' => __( 'Crop', 'imacon' ),
            'fa fa-crosshairs' => __( 'Crosshairs', 'imacon' ),
            'fa fa-css3' => __( 'Css3', 'imacon' ),
            'fa fa-cube' => __( 'Cube', 'imacon' ),
            'fa fa-cubes' => __( 'Cubes', 'imacon' ),
            'fa fa-cutlery' => __( 'Cutlery', 'imacon' ),
            'fa fa-dashcube' => __( 'Dashcube', 'imacon' ),
            'fa fa-database' => __( 'Database', 'imacon' ),
            'fa fa-delicious' => __( 'Delicious', 'imacon' ),
            'fa fa-desktop' => __( 'Desktop', 'imacon' ),
            'fa fa-deviantart' => __( 'Deviantart', 'imacon' ),
            'fa fa-diamond' => __( 'Diamond', 'imacon' ),
            'fa fa-digg' => __( 'Digg', 'imacon' ),
            'fa fa-dot-circle-o' => __( 'Dot Circle O', 'imacon' ),
            'fa fa-download' => __( 'Download', 'imacon' ),
            'fa fa-dribbble' => __( 'Dribbble', 'imacon' ),
            'fa fa-dropbox' => __( 'Dropbox', 'imacon' ),
            'fa fa-drupal' => __( 'Drupal', 'imacon' ),
            'fa fa-eject' => __( 'Eject', 'imacon' ),
            'fa fa-ellipsis-h' => __( 'Ellipsis H', 'imacon' ),
            'fa fa-ellipsis-v' => __( 'Ellipsis V', 'imacon' ),
            'fa fa-empire' => __( 'Empire', 'imacon' ),
            'fa fa-envelope' => __( 'Envelope', 'imacon' ),
            'fa fa-envelope-o' => __( 'Envelope O', 'imacon' ),
            'fa fa-envelope-square' => __( 'Envelope Square', 'imacon' ),
            'fa fa-eraser' => __( 'Eraser', 'imacon' ),
            'fa fa-eur' => __( 'Eur', 'imacon' ),
            'fa fa-exchange' => __( 'Exchange', 'imacon' ),
            'fa fa-exclamation' => __( 'Exclamation', 'imacon' ),
            'fa fa-exclamation-circle' => __( 'Exclamation Circle', 'imacon' ),
            'fa fa-exclamation-triangle' => __( 'Exclamation Triangle', 'imacon' ),
            'fa fa-expand' => __( 'Expand', 'imacon' ),
            'fa fa-expeditedssl' => __( 'Expeditedssl', 'imacon' ),
            'fa fa-external-link' => __( 'External Link', 'imacon' ),
            'fa fa-external-link-square' => __( 'External Link Square', 'imacon' ),
            'fa fa-eye' => __( 'Eye', 'imacon' ),
            'fa fa-eye-slash' => __( 'Eye Slash', 'imacon' ),
            'fa fa-eyedropper' => __( 'Eyedropper', 'imacon' ),
            'fa fa-facebook' => __( 'Facebook', 'imacon' ),
            'fa fa-facebook-official' => __( 'Facebook Official', 'imacon' ),
            'fa fa-facebook-square' => __( 'Facebook Square', 'imacon' ),
            'fa fa-fast-backward' => __( 'Fast Backward', 'imacon' ),
            'fa fa-fast-forward' => __( 'Fast Forward', 'imacon' ),
            'fa fa-fax' => __( 'Fax', 'imacon' ),
            'fa fa-female' => __( 'Female', 'imacon' ),
            'fa fa-fighter-jet' => __( 'Fighter Jet', 'imacon' ),
            'fa fa-file' => __( 'File', 'imacon' ),
            'fa fa-file-archive-o' => __( 'File Archive O', 'imacon' ),
            'fa fa-file-audio-o' => __( 'File Audio O', 'imacon' ),
            'fa fa-file-code-o' => __( 'File Code O', 'imacon' ),
            'fa fa-file-excel-o' => __( 'File Excel O', 'imacon' ),
            'fa fa-file-image-o' => __( 'File Image O', 'imacon' ),
            'fa fa-file-o' => __( 'File O', 'imacon' ),
            'fa fa-file-pdf-o' => __( 'File Pdf O', 'imacon' ),
            'fa fa-file-powerpoint-o' => __( 'File Powerpoint O', 'imacon' ),
            'fa fa-file-text' => __( 'File Text', 'imacon' ),
            'fa fa-file-text-o' => __( 'File Text O', 'imacon' ),
            'fa fa-file-video-o' => __( 'File Video O', 'imacon' ),
            'fa fa-file-word-o' => __( 'File Word O', 'imacon' ),
            'fa fa-files-o' => __( 'Files O', 'imacon' ),
            'fa fa-film' => __( 'Film', 'imacon' ),
            'fa fa-filter' => __( 'Filter', 'imacon' ),
            'fa fa-fire' => __( 'Fire', 'imacon' ),
            'fa fa-fire-extinguisher' => __( 'Fire Extinguisher', 'imacon' ),
            'fa fa-firefox' => __( 'Firefox', 'imacon' ),
            'fa fa-flag' => __( 'Flag', 'imacon' ),
            'fa fa-flag-checkered' => __( 'Flag Checkered', 'imacon' ),
            'fa fa-flag-o' => __( 'Flag O', 'imacon' ),
            'fa fa-flask' => __( 'Flask', 'imacon' ),
            'fa fa-flickr' => __( 'Flickr', 'imacon' ),
            'fa fa-floppy-o' => __( 'Floppy O', 'imacon' ),
            'fa fa-folder' => __( 'Folder', 'imacon' ),
            'fa fa-folder-o' => __( 'Folder O', 'imacon' ),
            'fa fa-folder-open' => __( 'Folder Open', 'imacon' ),
            'fa fa-folder-open-o' => __( 'Folder Open O', 'imacon' ),
            'fa fa-font' => __( 'Font', 'imacon' ),
            'fa fa-fontImacons' => __( 'FontImacons', 'imacon' ),
            'fa fa-forumbee' => __( 'Forumbee', 'imacon' ),
            'fa fa-forward' => __( 'Forward', 'imacon' ),
            'fa fa-foursquare' => __( 'Foursquare', 'imacon' ),
            'fa fa-frown-o' => __( 'Frown O', 'imacon' ),
            'fa fa-futbol-o' => __( 'Futbol O', 'imacon' ),
            'fa fa-gamepad' => __( 'Gamepad', 'imacon' ),
            'fa fa-gavel' => __( 'Gavel', 'imacon' ),
            'fa fa-gbp' => __( 'Gbp', 'imacon' ),
            'fa fa-genderless' => __( 'Genderless', 'imacon' ),
            'fa fa-get-pocket' => __( 'Get Pocket', 'imacon' ),
            'fa fa-gg' => __( 'Gg', 'imacon' ),
            'fa fa-gg-circle' => __( 'Gg Circle', 'imacon' ),
            'fa fa-gift' => __( 'Gift', 'imacon' ),
            'fa fa-git' => __( 'Git', 'imacon' ),
            'fa fa-git-square' => __( 'Git Square', 'imacon' ),
            'fa fa-github' => __( 'Github', 'imacon' ),
            'fa fa-github-alt' => __( 'Github Alt', 'imacon' ),
            'fa fa-github-square' => __( 'Github Square', 'imacon' ),
            'fa fa-glass' => __( 'Glass', 'imacon' ),
            'fa fa-globe' => __( 'Globe', 'imacon' ),
            'fa fa-google' => __( 'Google', 'imacon' ),
            'fa fa-google-plus' => __( 'Google Plus', 'imacon' ),
            'fa fa-google-plus-square' => __( 'Google Plus Square', 'imacon' ),
            'fa fa-google-wallet' => __( 'Google Wallet', 'imacon' ),
            'fa fa-graduation-cap' => __( 'Graduation Cap', 'imacon' ),
            'fa fa-gratipay' => __( 'Gratipay', 'imacon' ),
            'fa fa-h-square' => __( 'H Square', 'imacon' ),
            'fa fa-hacker-news' => __( 'Hacker News', 'imacon' ),
            'fa fa-hand-lizard-o' => __( 'Hand Lizard O', 'imacon' ),
            'fa fa-hand-o-down' => __( 'Hand O Down', 'imacon' ),
            'fa fa-hand-o-left' => __( 'Hand O Left', 'imacon' ),
            'fa fa-hand-o-right' => __( 'Hand O Right', 'imacon' ),
            'fa fa-hand-o-up' => __( 'Hand O Up', 'imacon' ),
            'fa fa-hand-paper-o' => __( 'Hand Paper O', 'imacon' ),
            'fa fa-hand-peace-o' => __( 'Hand Peace O', 'imacon' ),
            'fa fa-hand-pointer-o' => __( 'Hand Pointer O', 'imacon' ),
            'fa fa-hand-rock-o' => __( 'Hand Rock O', 'imacon' ),
            'fa fa-hand-scissors-o' => __( 'Hand Scissors O', 'imacon' ),
            'fa fa-hand-spock-o' => __( 'Hand Spock O', 'imacon' ),
            'fa fa-hdd-o' => __( 'Hdd O', 'imacon' ),
            'fa fa-header' => __( 'Header', 'imacon' ),
            'fa fa-headphones' => __( 'Headphones', 'imacon' ),
            'fa fa-heart' => __( 'Heart', 'imacon' ),
            'fa fa-heart-o' => __( 'Heart O', 'imacon' ),
            'fa fa-heartbeat' => __( 'Heartbeat', 'imacon' ),
            'fa fa-history' => __( 'History', 'imacon' ),
            'fa fa-home' => __( 'Home', 'imacon' ),
            'fa fa-hospital-o' => __( 'Hospital O', 'imacon' ),
            'fa fa-hourglass' => __( 'Hourglass', 'imacon' ),
            'fa fa-hourglass-end' => __( 'Hourglass End', 'imacon' ),
            'fa fa-hourglass-half' => __( 'Hourglass Half', 'imacon' ),
            'fa fa-hourglass-o' => __( 'Hourglass O', 'imacon' ),
            'fa fa-hourglass-start' => __( 'Hourglass Start', 'imacon' ),
            'fa fa-houzz' => __( 'Houzz', 'imacon' ),
            'fa fa-html5' => __( 'Html5', 'imacon' ),
            'fa fa-i-cursor' => __( 'I Cursor', 'imacon' ),
            'fa fa-ils' => __( 'Ils', 'imacon' ),
            'fa fa-inbox' => __( 'Inbox', 'imacon' ),
            'fa fa-indent' => __( 'Indent', 'imacon' ),
            'fa fa-industry' => __( 'Industry', 'imacon' ),
            'fa fa-info' => __( 'Info', 'imacon' ),
            'fa fa-info-circle' => __( 'Info Circle', 'imacon' ),
            'fa fa-inr' => __( 'Inr', 'imacon' ),
            'fa fa-instagram' => __( 'Instagram', 'imacon' ),
            'fa fa-internet-explorer' => __( 'Internet Explorer', 'imacon' ),
            'fa fa-ioxhost' => __( 'Ioxhost', 'imacon' ),
            'fa fa-italic' => __( 'Italic', 'imacon' ),
            'fa fa-joomla' => __( 'Joomla', 'imacon' ),
            'fa fa-jpy' => __( 'Jpy', 'imacon' ),
            'fa fa-jsfiddle' => __( 'Jsfiddle', 'imacon' ),
            'fa fa-key' => __( 'Key', 'imacon' ),
            'fa fa-keyboard-o' => __( 'Keyboard O', 'imacon' ),
            'fa fa-krw' => __( 'Krw', 'imacon' ),
            'fa fa-language' => __( 'Language', 'imacon' ),
            'fa fa-laptop' => __( 'Laptop', 'imacon' ),
            'fa fa-lastfm' => __( 'Lastfm', 'imacon' ),
            'fa fa-lastfm-square' => __( 'Lastfm Square', 'imacon' ),
            'fa fa-leaf' => __( 'Leaf', 'imacon' ),
            'fa fa-leanpub' => __( 'Leanpub', 'imacon' ),
            'fa fa-lemon-o' => __( 'Lemon O', 'imacon' ),
            'fa fa-level-down' => __( 'Level Down', 'imacon' ),
            'fa fa-level-up' => __( 'Level Up', 'imacon' ),
            'fa fa-life-ring' => __( 'Life Ring', 'imacon' ),
            'fa fa-lightbulb-o' => __( 'Lightbulb O', 'imacon' ),
            'fa fa-line-chart' => __( 'Line Chart', 'imacon' ),
            'fa fa-link' => __( 'Link', 'imacon' ),
            'fa fa-linkedin' => __( 'Linkedin', 'imacon' ),
            'fa fa-linkedin-square' => __( 'Linkedin Square', 'imacon' ),
            'fa fa-linux' => __( 'Linux', 'imacon' ),
            'fa fa-list' => __( 'List', 'imacon' ),
            'fa fa-list-alt' => __( 'List Alt', 'imacon' ),
            'fa fa-list-ol' => __( 'List Ol', 'imacon' ),
            'fa fa-list-ul' => __( 'List Ul', 'imacon' ),
            'fa fa-location-arrow' => __( 'Location Arrow', 'imacon' ),
            'fa fa-lock' => __( 'Lock', 'imacon' ),
            'fa fa-long-arrow-down' => __( 'Long Arrow Down', 'imacon' ),
            'fa fa-long-arrow-left' => __( 'Long Arrow Left', 'imacon' ),
            'fa fa-long-arrow-right' => __( 'Long Arrow Right', 'imacon' ),
            'fa fa-long-arrow-up' => __( 'Long Arrow Up', 'imacon' ),
            'fa fa-magic' => __( 'Magic', 'imacon' ),
            'fa fa-magnet' => __( 'Magnet', 'imacon' ),
            'fa fa-male' => __( 'Male', 'imacon' ),
            'fa fa-map' => __( 'Map', 'imacon' ),
            'fa fa-map-marker' => __( 'Map Marker', 'imacon' ),
            'fa fa-map-o' => __( 'Map O', 'imacon' ),
            'fa fa-map-pin' => __( 'Map Pin', 'imacon' ),
            'fa fa-map-signs' => __( 'Map Signs', 'imacon' ),
            'fa fa-mars' => __( 'Mars', 'imacon' ),
            'fa fa-mars-double' => __( 'Mars Double', 'imacon' ),
            'fa fa-mars-stroke' => __( 'Mars Stroke', 'imacon' ),
            'fa fa-mars-stroke-h' => __( 'Mars Stroke H', 'imacon' ),
            'fa fa-mars-stroke-v' => __( 'Mars Stroke V', 'imacon' ),
            'fa fa-maxcdn' => __( 'Maxcdn', 'imacon' ),
            'fa fa-meanpath' => __( 'Meanpath', 'imacon' ),
            'fa fa-medium' => __( 'Medium', 'imacon' ),
            'fa fa-medkit' => __( 'Medkit', 'imacon' ),
            'fa fa-meh-o' => __( 'Meh O', 'imacon' ),
            'fa fa-mercury' => __( 'Mercury', 'imacon' ),
            'fa fa-microphone' => __( 'Microphone', 'imacon' ),
            'fa fa-microphone-slash' => __( 'Microphone Slash', 'imacon' ),
            'fa fa-minus' => __( 'Minus', 'imacon' ),
            'fa fa-minus-circle' => __( 'Minus Circle', 'imacon' ),
            'fa fa-minus-square' => __( 'Minus Square', 'imacon' ),
            'fa fa-minus-square-o' => __( 'Minus Square O', 'imacon' ),
            'fa fa-mobile' => __( 'Mobile', 'imacon' ),
            'fa fa-money' => __( 'Money', 'imacon' ),
            'fa fa-moon-o' => __( 'Moon O', 'imacon' ),
            'fa fa-motorcycle' => __( 'Motorcycle', 'imacon' ),
            'fa fa-mouse-pointer' => __( 'Mouse Pointer', 'imacon' ),
            'fa fa-music' => __( 'Music', 'imacon' ),
            'fa fa-neuter' => __( 'Neuter', 'imacon' ),
            'fa fa-newspaper-o' => __( 'Newspaper O', 'imacon' ),
            'fa fa-object-group' => __( 'Object Group', 'imacon' ),
            'fa fa-object-ungroup' => __( 'Object Ungroup', 'imacon' ),
            'fa fa-odnoklassniki' => __( 'Odnoklassniki', 'imacon' ),
            'fa fa-odnoklassniki-square' => __( 'Odnoklassniki Square', 'imacon' ),
            'fa fa-opencart' => __( 'Opencart', 'imacon' ),
            'fa fa-openid' => __( 'Openid', 'imacon' ),
            'fa fa-opera' => __( 'Opera', 'imacon' ),
            'fa fa-optin-monster' => __( 'Optin Monster', 'imacon' ),
            'fa fa-outdent' => __( 'Outdent', 'imacon' ),
            'fa fa-pagelines' => __( 'Pagelines', 'imacon' ),
            'fa fa-paint-brush' => __( 'Paint Brush', 'imacon' ),
            'fa fa-paper-plane' => __( 'Paper Plane', 'imacon' ),
            'fa fa-paper-plane-o' => __( 'Paper Plane O', 'imacon' ),
            'fa fa-paperclip' => __( 'Paperclip', 'imacon' ),
            'fa fa-paragraph' => __( 'Paragraph', 'imacon' ),
            'fa fa-pause' => __( 'Pause', 'imacon' ),
            'fa fa-paw' => __( 'Paw', 'imacon' ),
            'fa fa-paypal' => __( 'Paypal', 'imacon' ),
            'fa fa-pencil' => __( 'Pencil', 'imacon' ),
            'fa fa-pencil-square' => __( 'Pencil Square', 'imacon' ),
            'fa fa-pencil-square-o' => __( 'Pencil Square O', 'imacon' ),
            'fa fa-phone' => __( 'Phone', 'imacon' ),
            'fa fa-phone-square' => __( 'Phone Square', 'imacon' ),
            'fa fa-picture-o' => __( 'Picture O', 'imacon' ),
            'fa fa-pie-chart' => __( 'Pie Chart', 'imacon' ),
            'fa fa-pied-piper' => __( 'Pied Piper', 'imacon' ),
            'fa fa-pied-piper-alt' => __( 'Pied Piper Alt', 'imacon' ),
            'fa fa-pinterest' => __( 'Pinterest', 'imacon' ),
            'fa fa-pinterest-p' => __( 'Pinterest P', 'imacon' ),
            'fa fa-pinterest-square' => __( 'Pinterest Square', 'imacon' ),
            'fa fa-plane' => __( 'Plane', 'imacon' ),
            'fa fa-play' => __( 'Play', 'imacon' ),
            'fa fa-play-circle' => __( 'Play Circle', 'imacon' ),
            'fa fa-play-circle-o' => __( 'Play Circle O', 'imacon' ),
            'fa fa-plug' => __( 'Plug', 'imacon' ),
            'fa fa-plus' => __( 'Plus', 'imacon' ),
            'fa fa-plus-circle' => __( 'Plus Circle', 'imacon' ),
            'fa fa-plus-square' => __( 'Plus Square', 'imacon' ),
            'fa fa-plus-square-o' => __( 'Plus Square O', 'imacon' ),
            'fa fa-power-off' => __( 'Power Off', 'imacon' ),
            'fa fa-print' => __( 'Print', 'imacon' ),
            'fa fa-puzzle-piece' => __( 'Puzzle Piece', 'imacon' ),
            'fa fa-qq' => __( 'Qq', 'imacon' ),
            'fa fa-qrcode' => __( 'Qrcode', 'imacon' ),
            'fa fa-question' => __( 'Question', 'imacon' ),
            'fa fa-question-circle' => __( 'Question Circle', 'imacon' ),
            'fa fa-quote-left' => __( 'Quote Left', 'imacon' ),
            'fa fa-quote-right' => __( 'Quote Right', 'imacon' ),
            'fa fa-random' => __( 'Random', 'imacon' ),
            'fa fa-rebel' => __( 'Rebel', 'imacon' ),
            'fa fa-recycle' => __( 'Recycle', 'imacon' ),
            'fa fa-reddit' => __( 'Reddit', 'imacon' ),
            'fa fa-reddit-square' => __( 'Reddit Square', 'imacon' ),
            'fa fa-refresh' => __( 'Refresh', 'imacon' ),
            'fa fa-registered' => __( 'Registered', 'imacon' ),
            'fa fa-renren' => __( 'Renren', 'imacon' ),
            'fa fa-repeat' => __( 'Repeat', 'imacon' ),
            'fa fa-reply' => __( 'Reply', 'imacon' ),
            'fa fa-reply-all' => __( 'Reply All', 'imacon' ),
            'fa fa-retweet' => __( 'Retweet', 'imacon' ),
            'fa fa-road' => __( 'Road', 'imacon' ),
            'fa fa-rocket' => __( 'Rocket', 'imacon' ),
            'fa fa-rss' => __( 'Rss', 'imacon' ),
            'fa fa-rss-square' => __( 'Rss Square', 'imacon' ),
            'fa fa-rub' => __( 'Rub', 'imacon' ),
            'fa fa-safari' => __( 'Safari', 'imacon' ),
            'fa fa-scissors' => __( 'Scissors', 'imacon' ),
            'fa fa-search' => __( 'Search', 'imacon' ),
            'fa fa-search-minus' => __( 'Search Minus', 'imacon' ),
            'fa fa-search-plus' => __( 'Search Plus', 'imacon' ),
            'fa fa-sellsy' => __( 'Sellsy', 'imacon' ),
            'fa fa-server' => __( 'Server', 'imacon' ),
            'fa fa-share' => __( 'Share', 'imacon' ),
            'fa fa-share-alt' => __( 'Share Alt', 'imacon' ),
            'fa fa-share-alt-square' => __( 'Share Alt Square', 'imacon' ),
            'fa fa-share-square' => __( 'Share Square', 'imacon' ),
            'fa fa-share-square-o' => __( 'Share Square O', 'imacon' ),
            'fa fa-shield' => __( 'Shield', 'imacon' ),
            'fa fa-ship' => __( 'Ship', 'imacon' ),
            'fa fa-shirtsinbulk' => __( 'Shirtsinbulk', 'imacon' ),
            'fa fa-shopping-cart' => __( 'Shopping Cart', 'imacon' ),
            'fa fa-sign-in' => __( 'Sign In', 'imacon' ),
            'fa fa-sign-out' => __( 'Sign Out', 'imacon' ),
            'fa fa-signal' => __( 'Signal', 'imacon' ),
            'fa fa-simplybuilt' => __( 'Simplybuilt', 'imacon' ),
            'fa fa-sitemap' => __( 'Sitemap', 'imacon' ),
            'fa fa-skyatlas' => __( 'Skyatlas', 'imacon' ),
            'fa fa-skype' => __( 'Skype', 'imacon' ),
            'fa fa-slack' => __( 'Slack', 'imacon' ),
            'fa fa-sliders' => __( 'Sliders', 'imacon' ),
            'fa fa-slideshare' => __( 'Slideshare', 'imacon' ),
            'fa fa-smile-o' => __( 'Smile O', 'imacon' ),
            'fa fa-sort' => __( 'Sort', 'imacon' ),
            'fa fa-sort-alpha-asc' => __( 'Sort Alpha Asc', 'imacon' ),
            'fa fa-sort-alpha-desc' => __( 'Sort Alpha Desc', 'imacon' ),
            'fa fa-sort-amount-asc' => __( 'Sort Amount Asc', 'imacon' ),
            'fa fa-sort-amount-desc' => __( 'Sort Amount Desc', 'imacon' ),
            'fa fa-sort-asc' => __( 'Sort Asc', 'imacon' ),
            'fa fa-sort-desc' => __( 'Sort Desc', 'imacon' ),
            'fa fa-sort-numeric-asc' => __( 'Sort Numeric Asc', 'imacon' ),
            'fa fa-sort-numeric-desc' => __( 'Sort Numeric Desc', 'imacon' ),
            'fa fa-soundcloud' => __( 'Soundcloud', 'imacon' ),
            'fa fa-space-shuttle' => __( 'Space Shuttle', 'imacon' ),
            'fa fa-spinner' => __( 'Spinner', 'imacon' ),
            'fa fa-spoon' => __( 'Spoon', 'imacon' ),
            'fa fa-spotify' => __( 'Spotify', 'imacon' ),
            'fa fa-square' => __( 'Square', 'imacon' ),
            'fa fa-square-o' => __( 'Square O', 'imacon' ),
            'fa fa-stack-exchange' => __( 'Stack Exchange', 'imacon' ),
            'fa fa-stack-overflow' => __( 'Stack Overflow', 'imacon' ),
            'fa fa-star' => __( 'Star', 'imacon' ),
            'fa fa-star-half' => __( 'Star Half', 'imacon' ),
            'fa fa-star-half-o' => __( 'Star Half O', 'imacon' ),
            'fa fa-star-o' => __( 'Star O', 'imacon' ),
            'fa fa-steam' => __( 'Steam', 'imacon' ),
            'fa fa-steam-square' => __( 'Steam Square', 'imacon' ),
            'fa fa-step-backward' => __( 'Step Backward', 'imacon' ),
            'fa fa-step-forward' => __( 'Step Forward', 'imacon' ),
            'fa fa-stethoscope' => __( 'Stethoscope', 'imacon' ),
            'fa fa-sticky-note' => __( 'Sticky Note', 'imacon' ),
            'fa fa-sticky-note-o' => __( 'Sticky Note O', 'imacon' ),
            'fa fa-stop' => __( 'Stop', 'imacon' ),
            'fa fa-street-view' => __( 'Street View', 'imacon' ),
            'fa fa-strikethrough' => __( 'Strikethrough', 'imacon' ),
            'fa fa-stumbleupon' => __( 'Stumbleupon', 'imacon' ),
            'fa fa-stumbleupon-circle' => __( 'Stumbleupon Circle', 'imacon' ),
            'fa fa-subscript' => __( 'Subscript', 'imacon' ),
            'fa fa-subway' => __( 'Subway', 'imacon' ),
            'fa fa-suitcase' => __( 'Suitcase', 'imacon' ),
            'fa fa-sun-o' => __( 'Sun O', 'imacon' ),
            'fa fa-superscript' => __( 'Superscript', 'imacon' ),
            'fa fa-table' => __( 'Table', 'imacon' ),
            'fa fa-tablet' => __( 'Tablet', 'imacon' ),
            'fa fa-tachometer' => __( 'Tachometer', 'imacon' ),
            'fa fa-tag' => __( 'Tag', 'imacon' ),
            'fa fa-tags' => __( 'Tags', 'imacon' ),
            'fa fa-tasks' => __( 'Tasks', 'imacon' ),
            'fa fa-taxi' => __( 'Taxi', 'imacon' ),
            'fa fa-television' => __( 'Television', 'imacon' ),
            'fa fa-tencent-weibo' => __( 'Tencent Weibo', 'imacon' ),
            'fa fa-terminal' => __( 'Terminal', 'imacon' ),
            'fa fa-text-height' => __( 'Text Height', 'imacon' ),
            'fa fa-text-width' => __( 'Text Width', 'imacon' ),
            'fa fa-th' => __( 'Th', 'imacon' ),
            'fa fa-th-large' => __( 'Th Large', 'imacon' ),
            'fa fa-th-list' => __( 'Th List', 'imacon' ),
            'fa fa-thumb-tack' => __( 'Thumb Tack', 'imacon' ),
            'fa fa-thumbs-down' => __( 'Thumbs Down', 'imacon' ),
            'fa fa-thumbs-o-down' => __( 'Thumbs O Down', 'imacon' ),
            'fa fa-thumbs-o-up' => __( 'Thumbs O Up', 'imacon' ),
            'fa fa-thumbs-up' => __( 'Thumbs Up', 'imacon' ),
            'fa fa-ticket' => __( 'Ticket', 'imacon' ),
            'fa fa-times' => __( 'Times', 'imacon' ),
            'fa fa-times-circle' => __( 'Times Circle', 'imacon' ),
            'fa fa-times-circle-o' => __( 'Times Circle O', 'imacon' ),
            'fa fa-tint' => __( 'Tint', 'imacon' ),
            'fa fa-toggle-off' => __( 'Toggle Off', 'imacon' ),
            'fa fa-toggle-on' => __( 'Toggle On', 'imacon' ),
            'fa fa-trademark' => __( 'Trademark', 'imacon' ),
            'fa fa-train' => __( 'Train', 'imacon' ),
            'fa fa-transgender' => __( 'Transgender', 'imacon' ),
            'fa fa-transgender-alt' => __( 'Transgender Alt', 'imacon' ),
            'fa fa-trash' => __( 'Trash', 'imacon' ),
            'fa fa-trash-o' => __( 'Trash O', 'imacon' ),
            'fa fa-tree' => __( 'Tree', 'imacon' ),
            'fa fa-trello' => __( 'Trello', 'imacon' ),
            'fa fa-tripadvisor' => __( 'Tripadvisor', 'imacon' ),
            'fa fa-trophy' => __( 'Trophy', 'imacon' ),
            'fa fa-truck' => __( 'Truck', 'imacon' ),
            'fa fa-try' => __( 'Try', 'imacon' ),
            'fa fa-tty' => __( 'Tty', 'imacon' ),
            'fa fa-tumblr' => __( 'Tumblr', 'imacon' ),
            'fa fa-tumblr-square' => __( 'Tumblr Square', 'imacon' ),
            'fa fa-twitch' => __( 'Twitch', 'imacon' ),
            'fa fa-twitter' => __( 'Twitter', 'imacon' ),
            'fa fa-twitter-square' => __( 'Twitter Square', 'imacon' ),
            'fa fa-umbrella' => __( 'Umbrella', 'imacon' ),
            'fa fa-underline' => __( 'Underline', 'imacon' ),
            'fa fa-undo' => __( 'Undo', 'imacon' ),
            'fa fa-university' => __( 'University', 'imacon' ),
            'fa fa-unlock' => __( 'Unlock', 'imacon' ),
            'fa fa-unlock-alt' => __( 'Unlock Alt', 'imacon' ),
            'fa fa-upload' => __( 'Upload', 'imacon' ),
            'fa fa-usd' => __( 'Usd', 'imacon' ),
            'fa fa-user' => __( 'User', 'imacon' ),
            'fa fa-user-md' => __( 'User Md', 'imacon' ),
            'fa fa-user-plus' => __( 'User Plus', 'imacon' ),
            'fa fa-user-secret' => __( 'User Secret', 'imacon' ),
            'fa fa-user-times' => __( 'User Times', 'imacon' ),
            'fa fa-users' => __( 'Users', 'imacon' ),
            'fa fa-venus' => __( 'Venus', 'imacon' ),
            'fa fa-venus-double' => __( 'Venus Double', 'imacon' ),
            'fa fa-venus-mars' => __( 'Venus Mars', 'imacon' ),
            'fa fa-viacoin' => __( 'Viacoin', 'imacon' ),
            'fa fa-video-camera' => __( 'Video Camera', 'imacon' ),
            'fa fa-vimeo' => __( 'Vimeo', 'imacon' ),
            'fa fa-vimeo-square' => __( 'Vimeo Square', 'imacon' ),
            'fa fa-vine' => __( 'Vine', 'imacon' ),
            'fa fa-vk' => __( 'Vk', 'imacon' ),
            'fa fa-volume-down' => __( 'Volume Down', 'imacon' ),
            'fa fa-volume-off' => __( 'Volume Off', 'imacon' ),
            'fa fa-volume-up' => __( 'Volume Up', 'imacon' ),
            'fa fa-weibo' => __( 'Weibo', 'imacon' ),
            'fa fa-weixin' => __( 'Weixin', 'imacon' ),
            'fa fa-whatsapp' => __( 'Whatsapp', 'imacon' ),
            'fa fa-wheelchair' => __( 'Wheelchair', 'imacon' ),
            'fa fa-wifi' => __( 'Wifi', 'imacon' ),
            'fa fa-wikipedia-w' => __( 'Wikipedia W', 'imacon' ),
            'fa fa-windows' => __( 'Windows', 'imacon' ),
            'fa fa-wordpress' => __( 'Wordpress', 'imacon' ),
            'fa fa-wrench' => __( 'Wrench', 'imacon' ),
            'fa fa-xing' => __( 'Xing', 'imacon' ),
            'fa fa-xing-square' => __( 'Xing Square', 'imacon' ),
            'fa fa-y-combinator' => __( 'Y Combinator', 'imacon' ),
            'fa fa-yahoo' => __( 'Yahoo', 'imacon' ),
            'fa fa-yelp' => __( 'Yelp', 'imacon' ),
            'fa fa-youtube' => __( 'Youtube', 'imacon' ),
            'fa fa-youtube-play' => __( 'Youtube Play', 'imacon' ),
            'fa fa-youtube-square' => __( 'Youtube Square', 'imacon' )
        ];

        return apply_filters( 'imacon/icons', $icons );

    }

}
